on:
  create:
    ref_types:
      - tag
  push:
    tags:
      - '*'
    branches-ignore:
      - '*'

#comment
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Install the packaging tools
        run: sudo npm i -g web-ext crx

      - name: Checkout code
        uses: actions/checkout@v2
      
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF/refs\/tags\//}
      
      - name: Set the version in chrome manifest
        run: |
            sed -i 's/version": ""/version": "${{ steps.get_version.outputs.version }}"/' manifest.chrome.json
      
      - name: Set the version in firefox manifest
        run: |
            sed -i 's/version": ""/version": "${{ steps.get_version.outputs.version }}"/' manifest.firefox.json
      
      - name: Create build directories
        run: mkdir build_chrome build_firefox
      
      - name: Copy manifest Firefox
        run: cp manifest.firefox.json build_firefox/manifest.json
      
      - name: Copy manifest Chrome
        run: cp manifest.chrome.json build_chrome/manifest.json
      
      - name: Copy files into Chrome dir
        run: cp -r popup icons scripts build_chrome/.
      
      - name: Copy files into Firefox dir
        run: cp -r popup icons scripts build_firefox/.
      
      - name: Package Chrome
        run: cd build_chrome && crx pack -o posttolemmy_chrome.crx && cd -
      
      - name: Package Firefox
        run: cd build_firefox && web-ext build && web-ext sign --api-key=${{ secrets.FIREFOX_KEY }} --api-secret=${{ secrets.FIREFOX_TOKEN }} && cd -
      
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.get_version.outputs.version }}
          release_name: POST to lemmy ${{ steps.get_version.outputs.version }}
          draft: false
          prerelease: false
      
      - name: Upload Chrome Package
        id: upload-chrome-package
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build_chrome/posttolemmy_chrome.crx
          asset_name: posttolemmy-${{ steps.get_version.outputs.version }}-chrome.crx
          asset_content_type: application/zip
      
      - name: Upload Firefox Package
        id: upload-firefox-package 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: build_firefox/web-ext-artifacts/post_to_lemmy-${{ steps.get_version.outputs.version }}-an+fx.xpi
          asset_name: posttolemmy-${{ steps.get_version.outputs.version }}-firefox.xpi
          asset_content_type: application/zip
            
        